---
kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager
data:
config.yml: |-
  global:
    resolve_timeout: 5m
    templates:
    - '/etc/alertmanager-templates/*.tmpl'
    route:
    group_by: ['alertname', 'kubernetes_namespace', '__address__']

    group_wait: 30s

    group_interval: 5m

    repeat_interval: 15m

    receiver: default

    routes:
    - match:
        severity: slack
      receiver: slack_alert
    - match:
        severity: email
      receiver: email_alert
    receivers:
    - name: 'default'
      slack_configs:
        - channel: '#general'
          text: '<!channel>{{ template "slack.devops.text" . }}'
          send_resolved: true
    - name: 'slack_alert'
      slack_configs:
        - channel: '#general'
          send_resolved: true
    - name: 'email_alert'
      email_configs:
        - to: 'mariemsbouiii40@gmail.com'
    inhibit_rules:
    - source_match:
        severity: 'critical'
      target_match:
        severity: 'warning'
      equal: ['alertname', 'kubernetes_namespace', '__address__']
---        
