---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  hosts: localhost
  require_ansible_repo: false
  ansible_verbose: true
  ansible_verbosity: 2
  require_chef_for_busser: false
  require_ruby_for_busser: false

verifier:
  ruby_bindir: '/usr/bin'

platforms:
  - name: 'ubuntu_16.04_x64'
    driver_config:
       box: 'ubuntu/xenial64'
       network:
          - [ 'private_network', { ip: '192.168.33.111' } ]
  - name: 'centos_7_x64'
    driver_config:
       box: 'centos/7'
       network:
          - [ 'private_network', { ip: '192.168.33.112' } ]
 
suites:
  - name: default
    attributes:
      tags:
        - kubernetes-setup
  - name: deploy_application
    attributes:
      tags:
        - kubernetes-config
  - name: deploy_monitors
    attributes:
      tags:
        - kubernetes-config
