
  - include: validate.yml
    tags:
      - kubernetes-setup

  - name: Install kubernetes using kubeadmn
    include: "{{ ansible_os_family | lower }}/kubeadm.yml"
    when: kubeadm_cmd_exists | failed
    tags:
      - kubernetes-setup
       
  - name: Initialize a kubernetes cluster
    command: kubeadm init
    when: kubernetes_cluster_exists | failed
    tags:
      - kubernetes-setup
    notify:
      - deploy network pod
   
  - name: Deploy application
    include: "common/deployment.yml"
    tags:
      - kubernetes-config

  - name: Deploy monitoring pods
    include: "common/monitoring_deployment.yml"
    tags:
      - kubernetes-config 
