- include: validate.yml
  tags:
    - kubernetes-setup

- name: Install kubernetes using kubeadmn
  include: "{{ ansible_os_family | lower }}/kubeadm.yml"
  when: kubeadm_cmd_exists | failed
  tags:
    - kubernetes-setup
      
- name: join the node to the cluster
  command: kubeadm join --token={{ token }} {{ master_ip }}
  tags:
    - kubernetes-setup
