  - name: RedHat | kubernetes repository 
    yum_repository:
      name: {{ kubernetes_redhat_repository_name }}
      description: {{ kubernetes_redhat_repository_description }}
      baseurl: http://yum.kubernetes.io/repos/kubernetes-el7-x86_64
      gpgcheck: yes
      enabled: yes
      repo_gpgcheck: yes 
      gpgkey:
         - https://packages.cloud.google.com/yum/doc/yum-key.gpg
         - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

  - name: RedHat | Install kubeadm and dependencies
    yum:
     name: {{item}}
     state: installed 
     with_items:
          - docker.io
          - kubelet
          - kubeadm
          - kubectl
          - kubernetes-cni
     update_cache: yes
     notify:
       - start docker service
       - start kubelet service
# pods are not scheduled on the master by default for security reasons, to schedule the pods on the master run 'kubectl taint nodes --all dedicated-'

   - name: RedHat | Schedule pods on the master
     command: kubectl taint nodes --all dedicated-

