- name: Check whether kubeadm is already installed
  shell: "command --skip-preflight-checks kubeadm init "
  ignore-errors: True
  register: kubeadm_cmd_exists
  changed_when: false
 
- name: Check whether kubernetes cluster exists 
  shell: "command kubectl cluster-info"
  ignore-errors: True
  register: kubernetes_cluster_exists
  changed_when: false

- debug:
    msg: 'It seems that kubeadm is already exists'
   when: kubeadm_cmd_exists.rc == 0
- debug:
    msg: 'It seems that a kubernetes cluster is already exists'
  when: kubernetes_cluster_exists.rc == 0


